apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.harbor.host }}": {
          "auth": "{{ printf "%s:%s" ".Values.harbor.secret.name" ".Values.harbor.secret.token" | b64enc }}"
        }
      }
    }
