environment: dev/test/prod

harbor:
  host: your_harbor_registry_host
  project: your_harbor_project_name
  secret:
    name: your_harbor_robot_account_name
    token: your_harbor_robot_account_token

bitbucket:
  host: your_bitbucket_server_host
  port: your_bitbucket_ssh_port
  branch: your_branch_name
  eventListener:
    nodePort: 30019
  secret:
    webhook: your_bitbucket_webhook_secret
    ssh: your_base64_encoded_bitbucket_ssh_private_key

pipeline:
  timeouts:
    pipeline: 1h0m0s
    tasks: 0h45m0s
    finally: 0h15m0s
  params:
    retries: 3
    delay: 3

workspace:
  size: 3Gi
