apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: refs-changed-tb
spec:
  params:
    - name: url
      value: "$(extensions.url)"
    - name: revision
      value: "$(extensions.revision)"
    - name: repository
      value: "$(extensions.repository)"
