apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-task
spec:
  workspaces:
    - name: source
      description: Workspace containing the repository
      readOnly: true
    - name: cache
      description: Workspace for caching image layers
  steps:
    - name: test
      image: moby/buildkit:latest
      securityContext:
        privileged: true
        appArmorProfile:
          type: Unconfined
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e

        echo -e "[⏳]: Running tests..."
        buildctl-daemonless.sh build \
          --frontend dockerfile.v0 \
          --local context="." \
          --local dockerfile="{{ .Values.project.dockerfile.path }}" \
          --opt filename={{ .Values.project.dockerfile.name }} \
          --opt target="{{ .Values.project.dockerfile.testStage }}" \
          --export-cache type=local,dest="$(workspaces.cache.path)",mode=max \
          --output type=oci,dest=/dev/null
        echo -e "[🟢]: Tests passed."
        echo -e "[🟢]: Build cache exported to '$(workspaces.cache.path)'.\n"
